# This script is used to run a game in which the winner of each point is
# generated by the function random

# -*- coding: utf-8 -*-
import random
import time
from player import Player
from game import Game

# Name 2 players
player1 = Player('ACC')
player2 = Player('TDF')

# Name this game
Round = Game(player1,player2)

# Loop until there is a winner
while (Round._hasWinner() == False):    
    # Generate a random variable to find the winner of a ball
    # 0 <= random.random() < 1, so we can take 0.5 as a half
    if (random.random() < 0.5):
        nameWinner = player1.name;
    else:
        nameWinner = player2.name;
    # Calculate scores and print results
    Round.winPoint(nameWinner);


# When a winner is founda, quit loop and end this round
winner = Round.winner;
print (winner.name +  ' wins this round');

