# This script is used to run a game in which the winner of each point is
# generated by the function random

# -*- coding: utf-8 -*-
import random
import time
from player import Player
from game import Game

# Name 2 players for a round of tennis
name_player1 = "ACC";
name_player2 = "TDF";
player1 = Player(name_player1)
player2 = Player(name_player2)
Round = Game(player1,player2)
print ("Round begins, " + name_player1 + " vs " + name_player2 + ":")
# Loop until there is a winner
while (Round._hasWinner() == False):    
    # Generate a random variable to find the winner of a ball
    # 0 <= random.random() < 1, so we can take 0.5 as a half
    if (random.random() < 0.5):
        nameWinner = player1.name;
    else:
        nameWinner = player2.name;
    # Calculate scores and print results
    Round.winPoint(nameWinner);


# When a winner is founda, quit loop and end this round
winner = Round.winner;
print (winner.name +  ' wins this round');

